language: go

go:
  - "master"
  - "1.x"
  - "1.12.x"

go_import_path: github.com/thebotguys/golang-syscoin-rpc-client
sudo: false

env:
  - GO111MODULE=on
  - GOPATH=/home/travis/gopath/.cache

cache:
  directories:
    - /home/travis/gopath/.cache
    
script:
 - go build
 - go test -v ./...