language: go

go:
  - "master"
  - "1.x"
  - "1.11.x"

before_install: go get -t ./...
go_import_path: github.com/thebotguys/golang-syscoin-rpc-client

sudo: false
script:
 - go build
 - go test -v ./...